version: '3.8'
volumes:
  certs:
    driver: local
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:${STACK_VERSION}
    container_name: filebeat_order_system
    user: root
    volumes:
      - certs:/usr/share/filebeat/certs
      - '../../../var/filebeat/log/:/var/log/:ro'
      - '../../../var/filebeat/docker.sock:/var/run/docker.sock'
      - '../../../var/logs/:/var/lib/docker/containers/logs:ro'
      - './filebeat.yml:/usr/share/filebeat/filebeat.yml'
    environment:
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=https://es01:9200
      - KIBANA_HOSTS=http://kibana:5601
      - LOGSTASH_HOSTS=http://logstash01:9600