version: '3.9'
services:
  db:
    image: postgres:16.0-alpine
    container_name: lg-labs-db
    environment:
      - POSTGRES_USER=lglabs
      - POSTGRES_PASSWORD=lgpass
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local