version: '3.9'
services:
  db:
    image: postgres:16.0-alpine
    container_name: lg-labs-db
    environment:
      - POSTGRES_USER=lglabs
      - POSTGRES_PASSWORD=lgpass
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: PgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: lg@labx.com
      PGADMIN_DEFAULT_PASSWORD: lgpass
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5011:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    links:
      - db:pgsql-server
volumes:
  db:
    driver: local
  pgadmin:
    driver: local