version: '3.9'
services:
  promtail:
    image: "grafana/promtail:2.4.2"
    volumes:
      - '../../../build/:/temp/log'
      - ./promtail.yml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.8.1-arm64
    container_name: filebeat_order_system
    user: root
    volumes:
      - '../../../var/filebeat/log/:/var/log/:ro'
      - '../../../var/filebeat/docker.sock:/var/run/docker.sock'
      - '../../../build/:/var/lib/docker/containers/logs:ro'
      - './etc/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml'